version: '3.8'

services:
  # Бэкенд FastAPI
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
      DATABASE_URL: ${DATABASE_URL}
      APP_TITLE: ${APP_TITLE}
      APP_NAME: ${APP_NAME}
      ENV: ${ENV}
      DEBUG: ${DEBUG}
      SENTRY_DSN: ${SENTRY_DSN}
      PROMETHEUS_METRICS_KEY: ${PROMETHEUS_METRICS_KEY}
    networks:
      - proxy
    restart: unless-stopped

  # Фронтенд React с интегрированной игрой 21
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - proxy
    restart: unless-stopped

  # Игра 21 (Blackjack)
  game-21:
    build:
      context: ./game
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - proxy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  proxy:
    name: proxy # Specifies the external network to connect to
    external: true # Indicates that the network is external


    # 3jepYKmWzrpkHlIz5_edM1yMA9UdXbALBKE39-jH