services:
  # Бэкенд FastAPI
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
      DATABASE_URL: ${DATABASE_URL}
      APP_TITLE: ${APP_TITLE}
      APP_NAME: ${APP_NAME}
      ENV: ${ENV}
      DEBUG: ${DEBUG}
      SENTRY_DSN: ${SENTRY_DSN}
      PROMETHEUS_METRICS_KEY: ${PROMETHEUS_METRICS_KEY}
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels: 
      - "traefik.enable=true" # Enable Traefik on this service
      - "traefik.http.routers.backend.entrypoints=http" # Define HTTP entrypoint
      - "traefik.http.routers.backend.rule=Host(`api.pyramidgames.fun`)" # Host rule for routing
      - "traefik.http.middlewares.backend-https-redirect.redirectscheme.scheme=https" # Redirect HTTP to HTTPS
      - "traefik.http.routers.backend.middlewares=backend-https-redirect" # Apply HTTPS redirect middleware
      - "traefik.http.routers.backend-secure.entrypoints=https" # Secure entrypoint for HTTPS
      - "traefik.http.routers.backend-secure.rule=Host(`api.pyramidgames.fun`)"  # Host rule for secure routing
      - "traefik.http.routers.backend-secure.tls=true" # Enable TLS for secure connection
      - "traefik.http.routers.backend-secure.service=backend" # Internal service for Traefik API
      - "traefik.http.services.backend.loadbalancer.server.port=8000" # Internal service for Traefik API
      - "traefik.docker.network=proxy" # Internal service for Traefik API

  # Фронтенд React с интегрированной игрой 21
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    # ports:
    #   - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels: 
      - "traefik.enable=true" # Enable Traefik on this service
      - "traefik.http.routers.frontend.entrypoints=http" # Define HTTP entrypoint
      - "traefik.http.routers.frontend.rule=Host(`pyramidgames.fun`)" # Host rule for routing
      - "traefik.http.middlewares.frontend-https-redirect.redirectscheme.scheme=https" # Redirect HTTP to HTTPS
      - "traefik.http.routers.frontend.middlewares=frontend-https-redirect" # Apply HTTPS redirect middleware
      - "traefik.http.routers.frontend-secure.entrypoints=https" # Secure entrypoint for HTTPS
      - "traefik.http.routers.frontend-secure.rule=Host(`pyramidgames.fun`)"  # Host rule for secure routing
      - "traefik.http.routers.frontend-secure.tls=true" # Enable TLS for secure connection
      - "traefik.http.routers.frontend-secure.service=frontend" # Internal service for Traefik API
      - "traefik.http.services.frontend.loadbalancer.server.port=3000" # Internal service for Traefik API
      - "traefik.docker.network=proxy" # Internal service for Traefik API

  # Игра 21 (Blackjack)
  game-21:
    build:
      context: ./game_new
      dockerfile: Dockerfile
    # ports:
    #   - "5001:5000"
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels: 
      - "traefik.enable=true" # Enable Traefik on this service
      - "traefik.http.routers.game-21.entrypoints=http" # Define HTTP entrypoint
      - >-
        traefik.http.routers.game-21.rule=Host(`game.pyramidgames.fun`) || (Host(`game.pyramidgames.fun`) && PathPrefix(`/js`))
      - "traefik.http.middlewares.game-21-https-redirect.redirectscheme.scheme=https" # Redirect HTTP to HTTPS
      - "traefik.http.routers.game-21.middlewares=game-21-https-redirect" # Apply HTTPS redirect middleware
      - "traefik.http.routers.game-21-secure.entrypoints=https" # Secure entrypoint for HTTPS
      - >-
        traefik.http.routers.game-21-secure.rule=Host(`game.pyramidgames.fun`) || (Host(`game.pyramidgames.fun`) && PathPrefix(`/js`))
      - "traefik.http.routers.game-21-secure.tls=true" # Enable TLS for secure connection
      - "traefik.http.routers.game-21-secure.service=game-21" # Internal service for Traefik API
      - "traefik.http.services.game-21.loadbalancer.server.port=5001" # Internal service for Traefik API
      - "traefik.docker.network=proxy" # Internal service for Traefik API

volumes:
  postgres_data:

networks:
  proxy:
    name: proxy # Specifies the external network to connect to
    external: true # Indicates that the network is external


    # 3jepYKmWzrpkHlIz5_edM1yMA9UdXbALBKE39-jH