"""comment

Revision ID: b267ecb9423c
Revises: 
Create Date: 2023-12-04 20:34:17.071024

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b267ecb9423c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dummy_model")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
