"""Add cards_drawn field to game_sessions

Revision ID: 3d237950df56
Revises: 741569d1fbee
Create Date: 2025-07-28 00:54:08.555387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d237950df56'
down_revision = '741569d1fbee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('cards_drawn', sa.Integer(), nullable=True))
    op.execute("UPDATE game_sessions SET cards_drawn = 0 WHERE cards_drawn IS NULL")
    op.alter_column('game_sessions', 'cards_drawn', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'cards_drawn')
    # ### end Alembic commands ###
