"""Add users table and bet fields to game_sessions

Revision ID: 64f1cc6585b7
Revises: 3d237950df56
Create Date: 2025-07-28 09:39:44.223016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f1cc6585b7'
down_revision = '3d237950df56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.add_column('game_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('bet_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'bet_amount')
    op.drop_column('game_sessions', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
