"""Add game_sessions table

Revision ID: 741569d1fbee
Revises: b267ecb9423c
Create Date: 2025-07-13 23:19:24.108060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741569d1fbee'
down_revision = 'b267ecb9423c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_cards', sa.JSON(), nullable=False),
    sa.Column('dealer_cards', sa.JSON(), nullable=False),
    sa.Column('player_score', sa.Integer(), nullable=False),
    sa.Column('dealer_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
