services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command: -c 'max_connections=500'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


  postgres-test:
    image: postgres:16
    ports:
      - "25439:5432"
    env_file:
      - .env.test
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
  bcraft_network:
    external: true
